algoritmo "Enquanto faca Fatorial"
// Função :
// Autor :
// Data : 15/03/2026
// Seção de Declarações 
var
numero, contador: inteiro
fatorial: real
inicio

   escreval ("Digite um numero: ")
   leia (numero)
   contador <- 1
   fatorial <- numero
   
   Enquanto (contador<numero) Faca
    fatorial <- fatorial * contador
    contador <- contador +1
   FimEnquanto
   Escreval ("Fatorial do " , numero , " é " , fatorial , ".")
fimalgoritmo
