algoritmo "  "
// Função :
// Autor :
// Data : 08/03/2026
// Seção de Declarações 
var
numero,resultado:inteiro
inicio
        resultado<-0

      Escreval("Digite um numero: ")
      leia(numero)

      Enquanto numero <> 5 Faca
      
      resultado <- resultado + numero
      
      Escreval("digite o numero")
      leia (numero)
      
  FimEnquanto
  
  escreval ("Total: " , resultado)
fimalgoritmo
