algoritmo "Media aluno usando enquanto"
// Função :
// Autor :
// Data : 14/03/2026
// Seção de Declarações 
var
aluno:caractere
nota,somaNota:real
contador:inteiro
inicio
      nota <- 0

      Escreval ("Digite o nome do aluno: ")
      Leia (aluno)
        contador <-1
      enquanto (contador <5)faca
      
      escreval ("digite a nota", contador , ": ")
      leia (nota)
      somaNota <- somaNota + nota
      contador<-contador + 1


      Escreval ("Aluno: ",aluno)
       Escreval ("Media", somaNota/4)
       Se   (somaNota>7)entao
       Escreval ("Aluno aprovado!")
       Senao
       Escreval ("Aluno reprovado!")
       Fimse
       FimEnquanto
fimalgoritmo
