algoritmo "Tabuada"
// Função :
// Autor :
// Data : 15/03/2026
// Seção de Declarações 
var
numero: real
contador: inteiro
tabuada: real
inicio

      contador <- 1

      Escreval ("digite um numero para obter sua tabuada: ")
      leia (numero)

      Enquanto (contador<=10) Faca
      tabuada <- (numero * contador)
       escreval ( numero , "x" , contador, " = " , tabuada)
      contador <- contador + 1
      FimEnquanto

fimalgoritmo
