algoritmo " Teste das cores função Se  "
// Função :
// Autor :
// Data : 18/02/2026
// Seção de Declarações 
var

  cor : caractere
   
inicio
                 Escreval("escreva uma cor :")
                  leia (cor)

      Se (cor = "azul") Entao
      Escreval ("a cor é azul!!")

      Senao

      Se (cor = "amarelo")  Entao
      Escreval ("cor amarelo")

      Senao
      Escreval( "cor invalida" )

      FimSe

fimalgoritmo



