algoritmo "tipos de dados"
// Função :
// Autor :
// Data : 17/02/2026
// Seção de Declarações 
var


   quantidade : inteiro
   preco : real
   moeda :caractere
   totalAPagar : real
   Produto: caractere
   cliente : caractere
   compraEefetuada : logico
inicio

      quantidade <- 2
      preco <- 89.90
      moeda <- "R$"
      totalAPagar <-  quantidade * preco
      cliente  <- "Luiza"
       Produto <- " BOLSA"
      compraEefetuada <- VERDADEIRO
      
      Escreval(quantidade)
      Escreval (preco)
      Escreval (totalApagar)
      Escreval (cliente)
      escreval (produto)
      Escreval (compraEefetuada)
      Escreval
      Escreval
      Escreval ("A cliente ", cliente, " comprou ", quantidade , " " ,Produto , " vai pagar total de ", moeda , totalApagar)
      
      
      
      




fimalgoritmo

