algoritmo "Vetor exemplos"
// Função :
// Autor :
// Data : 28/03/2026
// Seção de Declarações 
var

 letraDigitada:vetor [1..4] de caractere
 indice:inteiro
inicio


      para indice de 1 ate 4 faca
      escreval ("digite uma letra")
      leia (letraDigitada [indice])
      FimPara
      Escreval ("letra primeira posição " , letraDigitada [1])
      Escreval ("letra segunda posição " , letraDigitada [2])
      Escreval ("letra terceira posição " , letraDigitada [3])
      Escreval ("letra quarta posição " , letraDigitada [4])
fimalgoritmo
